select SAMPLEID, PSENERGY, DESCRIPTION, FILENAME, ASSAYDATE, CREATIONDATE from CI_PXR_CAM_PEAK_RECORD 
INNER JOIN (select SAMPLEID, DESCRIPTION from CI_PXD_SAMPLEINFORMATION) USING (SAMPLEID)
INNER JOIN (select SAMPLEID, FILENAME, ASSAYDATE, CREATIONDATE from CI_PXD_SAMPLE) USING (SAMPLEID)
where PSENERGY LIKE '686%';